import emberPlugin from 'eslint-plugin-ember';
import regexpPlugin from 'eslint-plugin-regexp';

export default [
    {
        plugins: {
            ember: emberPlugin,
            regexp: regexpPlugin
        },
        rules: {
            // Ember rules
            "ember/no-volatile-computed-properties": "error",
            "ember/no-assignment-of-untracked-properties-used-in-tracking-contexts": "error",
            "ember/no-restricted-resolver-tests": "error",
            "ember/no-component-lifecycle-hooks": "error",
            "ember/no-incorrect-calls-with-inline-anonymous-functions": "error",
            "ember/new-module-imports": "error",
            "ember/no-invalid-test-waiters": "error",
            "ember/routes-segments-snake-case": "error",
            "ember/no-settled-after-test-helper": "error",
            "ember/no-test-support-import": "error",
            "ember/closure-actions": "error",
            "ember/no-string-prototype-extensions": "error",
            "ember/no-deeply-nested-dependent-keys-with-each": "error",
            "ember/no-empty-glimmer-component-classes": "error",
            "ember/no-mixins": "error",
            "ember/no-try-invoke": "error",
            "ember/no-observers": "error",
            "ember/use-ember-data-rfc-395-imports": "error",
            "ember/no-on-calls-in-components": "error",
            "ember/no-new-mixins": "error",
            "ember/jquery-ember-run": "error",
            "ember/avoid-using-needs-in-controllers": "error",
            "ember/no-function-prototype-extensions": "error",
            "ember/no-attrs-in-components": "error",
            "ember/no-classic-classes": "error",
            "ember/classic-decorator-hooks": "error",
            "ember/require-valid-css-selector-in-test-helpers": "error",
            "ember/classic-decorator-no-classic-methods": "error",
            "ember/no-test-and-then": "error",
            "ember/no-actions-hash": "error",
            "ember/no-ember-super-in-es-classes": "error",
            "ember/no-duplicate-dependent-keys": "error",
            "ember/require-return-from-computed": "error",
            "ember/no-ember-testing-in-module-scope": "error",
            "ember/no-test-this-render": "error",
            "ember/avoid-leaking-state-in-ember-objects": "error",
            "ember/no-test-import-export": "error",

            // Regexp rules
            "regexp/no-dupe-disjunctions": "error",
            "regexp/no-useless-assertions": "error",
            "regexp/no-useless-lazy": "error",
            "regexp/no-non-standard-flag": "error",
            "regexp/no-escape-backspace": "error",
            "regexp/strict": "error",
            "regexp/no-optional-assertion": "error",
            "regexp/prefer-star-quantifier": "error",
            "regexp/no-empty-alternative": "error",
            "regexp/confusing-quantifier": "error",
            "regexp/no-useless-two-nums-quantifier": "error",
            "regexp/no-useless-set-operand": "error",
            "regexp/no-super-linear-backtracking": "error",
            "regexp/no-useless-range": "error",
            "regexp/no-useless-flag": "error",
            "regexp/no-useless-dollar-replacements": "error",
            "regexp/no-useless-non-capturing-group": "error",
            "regexp/prefer-set-operation": "error",
            "regexp/no-dupe-characters-character-class": "error",
            "regexp/no-obscure-range": "error",
            "regexp/prefer-d": "error",
            "regexp/no-invisible-character": "error",
            "regexp/no-missing-g-flag": "error",
            "regexp/no-useless-escape": "error",
            "regexp/no-invalid-regexp": "error",
            "regexp/prefer-predefined-assertion": "error",
            "regexp/no-empty-string-literal": "error",
            "regexp/no-empty-character-class": "error",
            "regexp/no-empty-lookarounds-assertion": "error",
            "regexp/no-useless-backreference": "error",
            "regexp/no-empty-group": "error",
            "regexp/negation": "error",
            "regexp/optimal-lookaround-quantifier": "error",
            "regexp/prefer-plus-quantifier": "error",
            "regexp/prefer-question-quantifier": "error",
            "regexp/no-trivially-nested-quantifier": "error",
            "regexp/no-trivially-nested-assertion": "error",
            "regexp/no-useless-quantifier": "error",
            "regexp/prefer-range": "error",
            "regexp/no-zero-quantifier": "error",
            "regexp/prefer-character-class": "error",
            "regexp/no-legacy-features": "error",
            "regexp/sort-flags": "error",
            "regexp/control-character-escape": "error",
            "regexp/match-any": "error",
            "regexp/no-potentially-useless-backreference": "error",
            "regexp/no-useless-string-literal": "error",
            "regexp/no-useless-character-class": "error",
            "regexp/no-empty-capturing-group": "error",
            "regexp/optimal-quantifier-concatenation": "error",
            "regexp/no-misleading-unicode-character": "error",
            "regexp/no-contradiction-with-assertion": "error",
            "regexp/no-misleading-capturing-group": "error",
            "regexp/no-lazy-ends": "error",
            "regexp/simplify-set-operations": "error",
            "regexp/prefer-unicode-codepoint-escapes": "error",
            "regexp/use-ignore-case": "error"
        }
    }
];