analyzer:
    errors:
        always_use_package_imports: error
        avoid_dynamic_calls: error
        avoid_empty_else: error
        avoid_print: error
        avoid_relative_lib_imports: error
        avoid_returning_null_for_future: error
        avoid_slow_async_io: error
        avoid_type_to_string: error
        avoid_types_as_parameter_names: error
        avoid_web_libraries_in_flutter: error
        cancel_subscriptions: error
        close_sinks: error
        collection_methods_unrelated_type: error
        comment_references: error
        control_flow_in_finally: error
        depend_on_referenced_packages: info
        diagnostic_describe_all_properties: error
        discarded_futures: error
        empty_statements: error
        hash_and_equals: error
        invariant_booleans: error
        iterable_contains_unrelated_type: error
        list_remove_unrelated_type: error
        literal_only_boolean_expressions: error
        no_adjacent_strings_in_list: error
        no_duplicate_case_values: error
        no_logic_in_create_state: error
linter:
    rules:
        always_declare_return_types: "true"
        always_put_control_body_on_new_line: "true"
        always_put_required_named_parameters_first: "true"
        always_require_non_null_named_parameters: "true"
        always_specify_types: "true"
        annotate_overrides: "true"
        avoid_annotating_with_dynamic: "true"
        avoid_as: "true"
        avoid_bool_literals_in_conditional_expressions: "true"
        avoid_catches_without_on_clauses: "true"
        avoid_catching_errors: "true"
        avoid_classes_with_only_static_members: "true"
        avoid_double_and_int_checks: "true"
        avoid_equals_and_hash_code_on_mutable_classes: "true"
        avoid_escaping_inner_quotes: "true"
        avoid_field_initializers_in_const_classes: "true"
        avoid_final_parameters: "true"
        avoid_function_literals_in_foreach_calls: "true"
        avoid_implementing_value_types: "true"
        avoid_init_to_null: "true"
        avoid_js_rounded_ints: "true"
        avoid_multiple_declarations_per_line: "true"
        avoid_null_checks_in_equality_operators: "true"
        avoid_positional_boolean_parameters: "true"
        avoid_private_typedef_functions: "true"
        avoid_redundant_argument_values: "true"
        avoid_renaming_method_parameters: "true"
        avoid_return_types_on_setters: "true"
        avoid_returning_null: "true"
        avoid_returning_null_for_void: "true"
        avoid_returning_this: "true"
        avoid_setters_without_getters: "true"
        avoid_shadowing_type_parameters: "true"
        avoid_single_cascade_in_expression_statements: "true"
        avoid_types_on_closure_parameters: "true"
        avoid_unnecessary_containers: "true"
        avoid_unused_constructor_parameters: "true"
        avoid_void_async: "true"
        await_only_futures: "true"
        camel_case_extensions: "true"
        camel_case_types: "true"
        cascade_invocations: "true"
        cast_nullable_to_non_nullable: "true"
        combinators_ordering: "true"
        conditional_uri_does_not_exist: "true"
        constant_identifier_names: "true"
        curly_braces_in_flow_control_structures: "true"
        dangling_library_doc_comments: "true"
        deprecated_consistency: "true"
        directives_ordering: "true"
        do_not_use_environment: "true"
        empty_catches: "true"
        empty_constructor_bodies: "true"
        enable_null_safety: "true"
        eol_at_end_of_file: "true"
        exhaustive_cases: "true"
        file_names: "true"
        flutter_style_todos: "true"
        implementation_imports: "true"
        implicit_call_tearoffs: "true"
        join_return_with_assignment: "true"
        leading_newlines_in_multiline_strings: "true"
        library_annotations: "true"
        library_names: "true"
        library_prefixes: "true"
        library_private_types_in_public_api: "true"
        lines_longer_than_80_chars: "true"
        missing_whitespace_between_adjacent_strings: "true"
        no_default_cases: "true"
        no_leading_underscores_for_library_prefixes: "true"
        no_leading_underscores_for_local_identifiers: "true"
        no_runtimeType_toString: "true"
        non_constant_identifier_names: "true"
