#!/bin/sh

set -eu

if [ -z "$(git status --porcelain)" ]; then
  echo "There no fixes, skipping PR..."
  exit 0
fi

echo "Creating PR with branch named $PR_BRANCH_NAME"

git checkout -b "$PR_BRANCH_NAME"
echo "Adding the changes"
git add .
echo "Committing the changes"
git commit -m "Auto fixes generated by codacy-cli"
echo "Pushing"
git push -u
echo "Creating PR..."
gh pr create --fill
