#!/bin/sh

set -eu

PR_BRANCH_NAME="$1"

if ! command -v gh; then
  echo "GitHub CLI needs to be installed for the PR creation to work. Exiting..."
  exit 1
fi

if [ -z "$(git status --porcelain)" ]; then
  echo "There no fixes, skipping PR..."
  exit 0
fi

echo "Creating PR with branch named $PR_BRANCH_NAME"

git checkout -b "$PR_BRANCH_NAME"
git add .
git commit -m "Auto fixes generated by codacy-cli"
git push -u
gh pr create --fill
