tools:
    - name: eslint
      languages: [Javascript]
      extensions: [.js, .jsm, .jsx, .mjs, .vue]
      files: []
    - name: lizard
      languages: [Java, Javascript, Python]
      extensions: [.java, .js, .jsm, .jsx, .mjs, .py, .vue]
      files: []
    - name: pmd
      languages: [Java, Javascript]
      extensions: [.java, .js, .jsm, .jsx, .mjs, .vue]
      files: []
    - name: pylint
      languages: [Python]
      extensions: [.py]
      files: []
    - name: semgrep
      languages: [Java, Javascript, Python]
      extensions: [.java, .js, .jsm, .jsx, .mjs, .py, .vue]
      files: []
    - name: trivy
      languages: [JSON, Java, Javascript, Python]
      extensions: [.java, .js, .jsm, .json, .jsx, .mjs, .py, .vue]
      files: [Pipfile.lock, gradle.lockfile, package-lock.json, package.json, pnpm-lock.yaml, poetry.lock, pom.xml, requirements.txt, uv.lock, yarn.lock]