tools:
    - name: eslint
      languages: [Javascript]
      extensions: [.js, .jsm, .jsx, .mjs, .vue]
      files: []
    - name: lizard
      languages: [Java, Javascript, Python]
      extensions: [.java, .js, .jsm, .jsx, .mjs, .py, .vue]
      files: []
    - name: pmd
      languages: [Java, Javascript]
      extensions: [.java, .js, .jsm, .jsx, .mjs, .vue]
      files: []
    - name: pylint
      languages: [Python]
      extensions: [.py]
      files: []
    - name: semgrep
      languages: [Java, Javascript, Python]
      extensions: [.java, .js, .jsm, .jsx, .mjs, .py, .vue]
      files: []
    - name: trivy
      languages: [JSON, Java, Javascript, Python]
      extensions: [.java, .js, .jsm, .json, .jsx, .mjs, .py, .vue]
      files: [.deps.json, Berksfile, Capfile, Cargo.lock, Cheffile, Directory.Packages.props, Dockerfile, Fastfile, Gemfile, Gemfile.lock, Guardfile, Package.resolved, Packages.props, Pipfile.lock, Podfile, Podfile.lock, Rakefile, Thorfile, Vagabondfile, Vagrantfile, build.sbt.lock, composer.lock, conan.lock, config.ru, go.mod, gradle.lockfile, mix.lock, package-lock.json, package.json, packages.config, packages.lock.json, pnpm-lock.yaml, poetry.lock, pom.xml, pubspec.lock, requirements.txt, uv.lock, yarn.lock]