tools:
    - name: eslint
      languages: [Javascript]
      extensions: [.js, .jsm, .jsx, .mjs, .vue]
    - name: lizard
      languages: [Java, Javascript, Python]
      extensions: [.java, .js, .jsm, .jsx, .mjs, .py, .vue]
    - name: pmd
      languages: [Java, Javascript]
      extensions: [.java, .js, .jsm, .jsx, .mjs, .vue]
    - name: pylint
      languages: [Python]
      extensions: [.py]
    - name: semgrep
      languages: [Java, Javascript, Python]
      extensions: [.java, .js, .jsm, .jsx, .mjs, .py, .vue]
    - name: trivy
      languages: [Multiple]
      extensions: []