on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Build CLI for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o cli-v2-linux ./cli-v2.go
      - name: Build CLI for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o cli-v2.exe ./cli-v2.go
      - name: Build CLI for macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o cli-v2-macos ./cli-v2.go
      - name: Upload CLI binaries
        uses: actions/upload-artifact@v4
        with:
          name: cli-binaries
          path: |
            cli-v2-linux
            cli-v2.exe
            cli-v2-macos

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Install dependencies from .codacy/codacy.yaml
        run: |
          go build ./cli-v2.go
          ./cli-v2 install
      - name: "Run tests"
        run: |
          go test -coverprofile=unit.coverage.out ./...
      - name: "Upload coverage to Codacy"
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r unit.coverage.out

  ittest:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download CLI binaries
        uses: actions/download-artifact@v4
        with:
          name: cli-binaries
          path: .
      - name: Select correct binary
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            # Keep the .exe extension for Windows
            echo "Using Windows binary with .exe extension"
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            mv cli-v2-macos cli-v2
          else
            mv cli-v2-linux cli-v2
          fi
      - name: Make binary executable
        if: matrix.os != 'windows-latest'
        run: chmod +x cli-v2
      - name: Debug Windows binary
        if: matrix.os == 'windows-latest'
        run: |
          dir
          echo "Binary exists check:"
          if (Test-Path cli-v2.exe) { Write-Host "Binary exists" } else { Write-Host "Binary not found" }
      - name: Setup Node.js for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies from .codacy/codacy.yaml
        if: matrix.os != 'windows-latest'
        run: |
          ./cli-v2 install
      - name: Install dependencies from .codacy/codacy.yaml (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Get-ChildItem
          Write-Host "Current directory contents:"
          dir
          Write-Host "Node.js version:"
          node --version
          Write-Host "Attempting to run CLI..."
          .\cli-v2.exe install

  release:
    needs: [test, ittest]
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: "Git Version"
        id: generate-version
        uses: codacy/git-version@2.8.0
      - name: "Tag version"
        run: |
          git tag ${{ steps.generate-version.outputs.version }}
          git push --tags "https://codacy:${{ secrets.GITHUB_TOKEN }}@github.com/codacy/codacy-cli-v2"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "latest"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
