on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0  # Needed for git history
      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
      - name: Build CLI for all platforms
        run: make build-all
      - name: Upload CLI binaries
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: cli-binaries
          path: |
            cli-v2-linux
            cli-v2.exe
            cli-v2-macos

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
      - name: Install dependencies from .codacy/codacy.yaml
        run: |
          make build
          ./cli-v2 install
      - name: "Run tests"
        run: |
          go test -coverprofile=unit.coverage.out ./...
      - name: "Upload coverage to Codacy"
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r unit.coverage.out

# For now we are not releasing the CLI, as we are making some quicker iterations
  release:
    needs: [test]
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
      - name: "Git Version"
        id: generate-version
        uses: codacy/git-version@80c816f11db8dea5e3a81025f598193015b51832 # 2.8.0
      - name: "Tag version"
        run: |
          git tag ${{ steps.generate-version.outputs.version }}
          git push --tags "https://codacy:${{ secrets.GITHUB_TOKEN }}@github.com/codacy/codacy-cli-v2"
      - name: Get Go version
        id: go-version
        run: echo "VERSION=$(go version | cut -d' ' -f3)" >> $GITHUB_OUTPUT
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811 # v5
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOVERSION: ${{ steps.go-version.outputs.VERSION }}
